
## Each step is marked by hyphen " - " ... you add hyphen and that thing will become step

name: First Action
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo " In First Job "

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Running main.py
        run: python main.py

## There is no point in Caching VENV ... because when pip install -r requirements.txt will always install at env.pythonLocation and it will not install in VENV
## Therefore it make sense to always cache env.pythonLocation

      - name: Caching Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/*requirements.txt') }}

      - name: Install requirements.txt Dependencies
        run: |
          pip install -r requirements.txt

      - name: Checking env.pythonLocation value
      - run: |
          echo ${{ env.pythonLocation }}

      - name: Checking PIP LIST
      - run:  pip list -v

      - name: Running Calculate power
        run: python CalculatePower.py



      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifiles
          path: temp


 ##     - run: python CalculatePower.py
 ##     - run: mlflow ui


## --------------------- Starting Second Job ----------------------------------------------------

  second-job:
    needs: [first-job]
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo " In Second Job"

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Reusing Previously Cached Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('**/*requirements.txt') }}

      - name: Install requirements.txt Dependencies
        run: |
          pip install -r requirements.txt

      - name: Running Calculate power
        run: python CalculatePower.py

