name: First Action
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo " Hello World "

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: ls -lrta

      - name: Runing main.py
        run: python main.py

      - name: Caching Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements.txt
        run: pip install -r requirements.txt

## Each step is marked by hyphen " - " ... you add hyphen and that thing will become step

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifiles
          path: temp


 ##     - run: python CalculatePower.py
 ##     - run: mlflow ui
